### ISSUE TITLE
Crashes when saving

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#118]
```
What steps will reproduce the problem?
1. New Template
2. Make a change
3. Save it--CRASH

What is the expected output? What do you see instead?
I'd like to be able to save and retrieve work.


What version of the product are you using? On what operating system?
XMind 3.0, Ubuntu 8.4


Please provide any additional information below.
Failed to load contents from file
-----------------------------
Time: 2009-10-20 17:22:24
XMind: 3.0.3
Java Version: 1.5.0
Java Vendor: Free Software Foundation, Inc.
Java Runtime: null
    Version: 1.5.0
Java VM: GNU libgcj
    Version: 4.2.4 (Ubuntu 4.2.4-1ubuntu3)
    Vendor: Free Software Foundation, Inc.
    Info: GNU libgcj 4.2.4 (Ubuntu 4.2.4-1ubuntu3)
Operating System: Linux 2.6.24-24-386 (i386)
Language: en
Country: null
-----------------------------
org.xmind.core.CoreException: org.xmind.core.CoreException:
gnu.xml.dom.ls.DomLSException: duplicate default namespace
   at
org.xmind.core.internal.dom.WorkbookLoader.checkChecksum(WorkbookLoader.java:433
)
   at
org.xmind.core.internal.dom.WorkbookLoader.doLoadXMLFile(WorkbookLoader.java:383
)
   at org.xmind.core.internal.dom.XMLLoader.loadXMLFile(XMLLoader.java:38)
   at
org.xmind.core.internal.dom.WorkbookLoader.loadContents(WorkbookLoader.java:176)
   at
org.xmind.core.internal.dom.WorkbookLoader.doLoad(WorkbookLoader.java:147)
   at org.xmind.core.internal.dom.WorkbookLoader.load(WorkbookLoader.java:126)
   at
org.xmind.core.internal.dom.WorkbookBuilderImpl.loadFromInputSource(WorkbookBuil
derImpl.java:297)
   at
org.xmind.core.internal.AbstractWorkbookBuilder.doLoadFromDirectory(AbstractWork
bookBuilder.java:132)
   at
org.xmind.core.internal.AbstractWorkbookBuilder.loadFromTempLocation(AbstractWor
kbookBuilder.java:242)
   at
org.xmind.ui.internal.editor.TempWorkbookLoader.loadWorkbook(TempWorkbookLoader.
java:52)
   at
org.xmind.ui.internal.editor.WorkbookRef.loadWorkbook(WorkbookRef.java:322)
   at
org.xmind.ui.internal.editor.MindMapEditor$LoadWorkbookJob.run(MindMapEditor.jav
a:1032)
   at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.xmind.core.CoreException: gnu.xml.dom.ls.DomLSException:
duplicate default namespace
   at
org.xmind.core.internal.dom.WorkbookLoader.doLoadXMLFile(WorkbookLoader.java:384
)
   ...11 more
Caused by: gnu.xml.dom.ls.DomLSException: duplicate default namespace
   at gnu.xml.dom.ls.DomLSParser.doParse(libgcj.so.81)
   at gnu.xml.dom.ls.DomLSParser.parse(libgcj.so.81)
   at gnu.xml.dom.DomDocumentBuilder.parse(libgcj.so.81)
   at
org.xmind.core.internal.dom.WorkbookLoader.doLoadXMLFile(WorkbookLoader.java:381
)
   ...11 more
Caused by: org.xml.sax.SAXParseException: duplicate default namespace
   at gnu.xml.stream.SAXParser.parse(libgcj.so.81)
   at gnu.xml.dom.ls.DomLSParser.doParse(libgcj.so.81)
   ...14 more
Caused by: javax.xml.stream.XMLStreamException: duplicate default namespace
   at gnu.xml.stream.XMLParser.error(libgcj.so.81)
   at gnu.xml.stream.XMLParser.error(libgcj.so.81)
   at gnu.xml.stream.XMLParser.readAttribute(libgcj.so.81)
   at gnu.xml.stream.XMLParser.readStartElement(libgcj.so.81)
   at gnu.xml.stream.XMLParser.next(libgcj.so.81)
   at gnu.xml.stream.XMLParser.hasNext(libgcj.so.81)
   at gnu.xml.stream.SAXParser.parse(libgcj.so.81)
   ...15 more


```

Original issue reported on code.google.com by `loretta....@gmail.com` on 20 Oct 2009 at 11:21

**Comment by frankshaka** [comment]
Closing this issue as it is too old.
