### ISSUE TITLE
saved mind map will not open

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#158]
```
What steps will reproduce the problem?
1. save
2. open while xmind is open
3. opps Failed to load contents

What is the expected output? What do you see instead?
oops message

What version of the product are you using? On what operating system?
3.1.1 on Mac OX 10.4.11

Please provide any additional information below.
Failed to load contents from file
-----------------------------
Time: 2010-02-24 10:46:39
XMind: 3.1.1 Pro
Java Version: 1.5.0_19
Java Vendor: Apple Computer, Inc.
Java Runtime: Java(TM) 2 Runtime Environment, Standard Edition
    Version: 1.5.0_19-b02-306
Java VM: Java HotSpot(TM) Client VM
    Version: 1.5.0_19-138
    Vendor: "Apple Computer, Inc."
    Info: mixed mode
Operating System: Mac OS X 10.4.11 (i386)
Language: en
Country: US
-----------------------------
java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:203)
    at java.util.zip.ZipFile.<init>(ZipFile.java:234)
    at
org.xmind.core.internal.dom.WorkbookBuilderImpl.doLoadFromFile(WorkbookBuilderIm
pl.java:216)
    at
org.xmind.core.internal.AbstractWorkbookBuilder.loadFromFile(AbstractWorkbookBui
lder.java:117)
    at
org.xmind.ui.internal.editor.FileStoreWorkbookAdapter.loadWorkbook(FileStoreWork
bookAdapter.java:37)
    at org.xmind.ui.internal.editor.WorkbookRef.loadWorkbook(WorkbookRef.java:338)
    at
org.xmind.ui.internal.editor.MindMapEditor$LoadWorkbookJob.run(MindMapEditor.jav
a:1013)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


```

Original issue reported on code.google.com by `energywi...@gmail.com` on 24 Feb 2010 at 6:58

**Comment by frankshaka** [comment]
Closing this issue as it is too old.
