### ISSUE TITLE
Impossible to load a large map made from scratch then saved

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#237]
```
What steps will reproduce the problem?
1. Make the mind map I joined as attached file from scratch 
2. save it and quit Xmind
3. open Xmind then load the map

What is the expected output? What do you see instead?

I expect to see my map but it is not the case. I suppose, this is because my 
map is quite large. There is a crash with the error message below:

"Oops! Echec du chargement de contenus depuis ce fichier.

Provoqué par 'org.xmind.core.CoreException': org.xmind.core.CoreException: 
gnu.xml.dom.ls.DomLSException: duplicate default namespace"

What version of the product are you using? On what operating system?

-----------------------------
Time: 2012-01-21 10:47:28
XMind: 3.2.1 Pro
Java Version: 1.5.0
Java Vendor: Free Software Foundation, Inc.
Java Runtime: null
    Version: 1.5.0
Java VM: GNU libgcj
    Version: 4.4.1
    Vendor: Free Software Foundation, Inc.
    Info: GNU libgcj 4.4.1
Operating System: Linux 2.6.31-23-generic (i386)
Language: fr
Country: null
-----------------------------


Please provide any additional information below.
org.xmind.core.CoreException: org.xmind.core.CoreException: 
gnu.xml.dom.ls.DomLSException: duplicate default namespace
   at org.xmind.core.internal.dom.WorkbookLoader.checkChecksum(WorkbookLoader.java:432)
   at org.xmind.core.internal.dom.WorkbookLoader.doLoadXMLFile(WorkbookLoader.java:382)
   at org.xmind.core.internal.dom.XMLLoader.loadXMLFile(XMLLoader.java:38)
   at org.xmind.core.internal.dom.WorkbookLoader.loadContents(WorkbookLoader.java:174)
   at org.xmind.core.internal.dom.WorkbookLoader.doLoad(WorkbookLoader.java:147)
   at org.xmind.core.internal.dom.WorkbookLoader.load(WorkbookLoader.java:126)
   at org.xmind.core.internal.dom.WorkbookBuilderImpl.loadFromInputSource(WorkbookBuilderImpl.java:298)
   at org.xmind.core.internal.dom.WorkbookBuilderImpl.doLoadFromFile(WorkbookBuilderImpl.java:218)
   at org.xmind.core.internal.AbstractWorkbookBuilder.loadFromFile(AbstractWorkbookBuilder.java:117)
   at org.xmind.ui.internal.editor.FileStoreWorkbookAdapter.loadWorkbook(FileStoreWorkbookAdapter.java:38)
   at org.xmind.ui.internal.editor.WorkbookRef.loadWorkbook(WorkbookRef.java:338)
   at org.xmind.ui.internal.editor.MindMapEditor$LoadWorkbookJob.run(MindMapEditor.java:1016)
   at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.xmind.core.CoreException: gnu.xml.dom.ls.DomLSException: 
duplicate default namespace
   at org.xmind.core.internal.dom.WorkbookLoader.doLoadXMLFile(WorkbookLoader.java:383)
   ...11 more
Caused by: gnu.xml.dom.ls.DomLSException: duplicate default namespace
   at gnu.xml.dom.ls.DomLSParser.doParse(libgcj.so.10)
   at gnu.xml.dom.ls.DomLSParser.parse(libgcj.so.10)
   at gnu.xml.dom.DomDocumentBuilder.parse(libgcj.so.10)
   at org.xmind.core.internal.dom.WorkbookLoader.doLoadXMLFile(WorkbookLoader.java:380)
   ...11 more
Caused by: org.xml.sax.SAXParseException: duplicate default namespace
   at gnu.xml.stream.SAXParser.parse(libgcj.so.10)
   at gnu.xml.dom.ls.DomLSParser.doParse(libgcj.so.10)
   ...14 more
Caused by: javax.xml.stream.XMLStreamException: duplicate default namespace
   at gnu.xml.stream.XMLParser.error(libgcj.so.10)
   at gnu.xml.stream.XMLParser.error(libgcj.so.10)
   at gnu.xml.stream.XMLParser.readAttribute(libgcj.so.10)
   at gnu.xml.stream.XMLParser.readStartElement(libgcj.so.10)
   at gnu.xml.stream.XMLParser.next(libgcj.so.10)
   at gnu.xml.stream.SAXParser.parse(libgcj.so.10)
   ...15 more


```

Original issue reported on code.google.com by `Edrisse....@gmail.com` on 21 Jan 2012 at 9:59

Attachments:
- [Diagramme.xmind](https://storage.googleapis.com/google-code-attachments/xmind3/issue-237/comment-0/Diagramme.xmind)

**Comment by frankshaka** [comment]
Closing this issue as it is too old.

**Comment by michael-ts** [comment]
@frankshaka  what a joke!
