### ISSUE TITLE
Cannot save files in XMind 8 beta 

### ISSUE THREAD

**Issue by bberberov** [xmindltd/xmind#270]
XMind 8 beta crashes when trying to save a file.  The exception is posted below.

```

java.lang.NullPointerException
    at org.xmind.ui.internal.e4handlers.SaveWorkbookAsHandler.saveWorkbookAs(SaveWorkbookAsHandler.java:203)
    at org.xmind.ui.internal.editor.MindMapEditor.doSaveAs(MindMapEditor.java:1503)
    at org.xmind.ui.internal.editor.MindMapEditor.doSaveAs(MindMapEditor.java:1490)
    at org.eclipse.ui.internal.handlers.SaveAsHandler.execute(SaveAsHandler.java:42)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:54)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5219)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4553)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4143)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.xmind.cathy.internal.CathyApplication.start(CathyApplication.java:137)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

Severity: error
Plug-in ID: org.xmind.ui.mindmap
Code: 0

== Environment ==
Time: 2016-10-22 14:52:29
XMind Distribution Pack: cathy_portable
XMind Build ID: B3.7.0.201610182138
Operating System: Linux 4.7.6-1-default (amd64)
Platform: linux.gtk.x86_64
Language: en
Country: US

== Product ==
Product ID: org.xmind.cathy.product
Application ID: org.xmind.cathy.application
Launcher: XMind

Command Line Arguments: -os
 linux
 -ws
 gtk
 -arch
 x86_64
 -showsplash
 -launcher
 /home/USERNAME/xmind/XMind_Linux_64bit/XMind
 -name
 XMind
 --launcher.library
 /home/USERNAME/xmind/XMind_Linux_64bit//../Commons/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.400.v20160518-1444/eclipse_1617.so
 -startup
 /home/USERNAME/xmind/XMind_Linux_64bit//../Commons/plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
 --launcher.overrideVmargs
 -exitdata
 b8002
 -configuration
 ./configuration
 -data
 ../Commons/data/workspace-cathy
 -vm
 /usr/bin/java

VM Arguments: -Dosgi.signedcontent.support=all
 -jar
 /home/USERNAME/xmind/XMind_Linux_64bit//../Commons/plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar


== Java Properties ==
Java Version: 1.8.0_101
Java Vendor: Oracle Corporation
Java Runtime: OpenJDK Runtime Environment
    Version: 1.8.0_101-b13
Java VM: OpenJDK 64-Bit Server VM
    Version: 25.101-b13
    Vendor: Oracle Corporation
    Info: mixed mode

```

**Comment by bberberov** [comment]
Appears to be fixed in the Release version.
