### ISSUE TITLE
Can't run Xmind in fedora-25

### ISSUE THREAD

**Issue by shgharib** [xmindltd/xmind#282]
I downloaded the xmind-8. but when i try to run, it just shows me the splash screen and error dialog.
how can I run it under fedora-25.

The log message, 
```

!SESSION 2016-11-29 01:01:59.451 -----------------------------------------------
eclipse.buildId=R3.7.0.201611010032
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data ../workspace

!ENTRY org.eclipse.osgi.compatibility.state.nl_pt_BR 2 0 2016-11-29 01:02:02.758
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_pt_BR [843]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_ja 2 0 2016-11-29 01:02:02.758
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_ja [841]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_zh_TW 2 0 2016-11-29 01:02:02.758
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_zh_TW [847]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_de 2 0 2016-11-29 01:02:02.759
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_de [837]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_ru 2 0 2016-11-29 01:02:02.759
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_ru [844]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_ko 2 0 2016-11-29 01:02:02.759
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_ko [842]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_da 2 0 2016-11-29 01:02:02.759
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_da [836]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_ar 2 0 2016-11-29 01:02:02.759
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_ar [835]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_fr 2 0 2016-11-29 01:02:02.759
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_fr [839]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_sl 2 0 2016-11-29 01:02:02.759
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_sl [845]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_es 2 0 2016-11-29 01:02:02.760
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_es [838]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_it 2 0 2016-11-29 01:02:02.760
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_it [840]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi.compatibility.state.nl_zh 2 0 2016-11-29 01:02:02.760
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nl_zh [846]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi 4 0 2016-11-29 01:02:02.761
!MESSAGE Application error
!STACK 1
java.awt.HeadlessException
	at sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:284)
	at org.xmind.cathy.internal.CathyApplication.captureAppSessionInfo(CathyApplication.java:188)
	at org.xmind.cathy.internal.CathyApplication.start(CathyApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by WolfangAukang** [comment]
I can run it on Fedora 25. Do you have the following dependencies installed?

- java-1.8.0-openjdk.x86_64
- lame
- glibc
- webkitgtk

**Comment by WolfangAukang** [comment]
For the headless exception, it seems you need the openjdk and set the alternatives to it.

**Comment by shgharib** [comment]
I already installed those packages except lame, I couldn't find lame in fedora repositories.

I already use openjdk.

**Comment by WolfangAukang** [comment]
Do you have RPM Fusion repositories enabled on your distro? I guess Lame comes from it.

And is openjdk set on alternatives?

**Comment by shgharib** [comment]
I installed lame, it's working now. Thank you @WolfangAukang .
