### ISSUE TITLE
java.lang.NullPointerException While drill down/out

### ISSUE THREAD

**Issue by maciejmatuszak** [xmindltd/xmind#298]
I am experiencing null pointer wile drill down or when moving out. 
So far I think it is related to adding marker or note. In one case I just added marker and this started to happen. After removing marker, it is ok. 
Now I made more extensive modifications and can not find the breaking change...
Let me know if I can help in some way.

An error has occurred. See error log for more details.

java.lang.NullPointerException
	at org.xmind.ui.internal.svgsupport.SVGImageFigure.getPreferredSize(SVGImageFigure.java:108)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:800)
	at org.xmind.ui.internal.layouts.TopicLayout.getChildPreferredSize(TopicLayout.java:283)
	at org.xmind.ui.internal.layouts.TopicLayout.fillIconTip(TopicLayout.java:219)
	at org.xmind.ui.internal.layouts.TopicLayout.fillLayoutData(TopicLayout.java:115)
	at org.xmind.gef.draw2d.AbstractReferencedLayout.getLayoutData(AbstractReferencedLayout.java:92)
	at org.xmind.ui.internal.layouts.TopicLayout.getNormalReferenceDescription(TopicLayout.java:342)
	at org.xmind.ui.internal.layouts.TopicLayout.getReferenceDescription(TopicLayout.java:306)
	at org.xmind.gef.draw2d.ReferencedFigure.getReferenceDescription(ReferencedFigure.java:91)
	at org.xmind.gef.draw2d.ReferencedFigure.calculateReference(ReferencedFigure.java:67)
	at org.xmind.gef.draw2d.ReferencedFigure.getReference(ReferencedFigure.java:60)
	at org.xmind.gef.draw2d.AbstractAnchor.getReferencePoint(AbstractAnchor.java:139)
	at org.xmind.ui.internal.decorations.CurvedRelationshipDecoration.reroute(CurvedRelationshipDecoration.java:67)
	at org.xmind.ui.decorations.AbstractRelationshipDecoration.reroute(AbstractRelationshipDecoration.java:83)
	at org.xmind.gef.draw2d.decoration.AbstractConnectionDecoration.reroute(AbstractConnectionDecoration.java:93)
	at org.xmind.gef.draw2d.decoration.AbstractConnectionDecoration.reroute(AbstractConnectionDecoration.java:85)
	at org.xmind.ui.decorations.AbstractRelationshipDecoration.reroute(AbstractRelationshipDecoration.java:71)
	at org.xmind.ui.internal.decorators.RelationshipDecorator.decorateRelationship(RelationshipDecorator.java:101)
	at org.xmind.ui.internal.decorators.RelationshipDecorator.decorateRelationship(RelationshipDecorator.java:64)
	at org.xmind.ui.internal.decorators.RelationshipDecorator.decorate(RelationshipDecorator.java:48)
	at org.xmind.gef.part.GraphicalEditPart.updateView(GraphicalEditPart.java:116)
	at org.xmind.ui.internal.mindmap.MindMapPartBase.updateView(MindMapPartBase.java:261)
	at org.xmind.gef.part.Part.refresh(Part.java:183)
	at org.xmind.ui.internal.mindmap.ConnectionPart.refresh(ConnectionPart.java:71)
	at org.xmind.ui.internal.mindmap.RelationshipPart.refresh(RelationshipPart.java:184)
	at org.xmind.ui.internal.mindmap.NodePart.refreshTargetConnections(NodePart.java:111)
	at org.xmind.ui.internal.mindmap.NodePart.refreshConnections(NodePart.java:100)
	at org.xmind.ui.internal.mindmap.NodePart.removeNotify(NodePart.java:90)
	at org.xmind.gef.part.Part.removeNotify(Part.java:102)
	at org.xmind.gef.part.Part.removeNotify(Part.java:102)
	at org.xmind.gef.part.Part.removeNotify(Part.java:102)
	at org.xmind.gef.part.Part.removeChild(Part.java:144)
	at org.xmind.gef.part.GraphicalRootEditPart.setContents(GraphicalRootEditPart.java:46)
	at org.xmind.ui.internal.mindmap.MindMapRootPart.setContents(MindMapRootPart.java:118)
	at org.xmind.gef.AbstractViewer.contentsChanged(AbstractViewer.java:594)
	at org.xmind.gef.AbstractViewer.inputChanged(AbstractViewer.java:572)
	at org.xmind.gef.GraphicalViewer.internalInputChanged(GraphicalViewer.java:506)
	at org.xmind.gef.GraphicalViewer.inputChanged(GraphicalViewer.java:488)
	at org.xmind.gef.AbstractViewer.setInput(AbstractViewer.java:556)
	at org.xmind.ui.internal.tools.MindMapSelectTool.drillDown(MindMapSelectTool.java:1092)
	at org.xmind.ui.internal.tools.MindMapSelectTool.handleDrillUp(MindMapSelectTool.java:1123)
	at org.xmind.ui.internal.tools.MindMapSelectTool.handleNonTargetedRequest(MindMapSelectTool.java:636)
	at org.xmind.gef.tool.AbstractTool.internalHandleRequest(AbstractTool.java:513)
	at org.xmind.gef.tool.AbstractTool.handleRequest(AbstractTool.java:506)
	at org.xmind.gef.EditDomain.internalHandleRequest(EditDomain.java:313)
	at org.xmind.gef.EditDomain$1.run(EditDomain.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.xmind.gef.EditDomain.ensureRequestHandling(EditDomain.java:298)
	at org.xmind.gef.EditDomain.handleRequest(EditDomain.java:279)
	at org.xmind.gef.EditDomain.handleRequest(EditDomain.java:274)
	at org.xmind.ui.internal.mindmap.DrillUpInfoItemContributor$IconTipDrillUpAction.run(DrillUpInfoItemContributor.java:32)
	at org.xmind.ui.internal.tools.MindMapSelectTool$2$1.run(MindMapSelectTool.java:251)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.xmind.ui.internal.tools.MindMapSelectTool$2.run(MindMapSelectTool.java:249)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.xmind.cathy.internal.CathyApplication.start(CathyApplication.java:145)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

Severity: error
Plug-in ID: org.eclipse.jface
Code: 0

== Environment ==
Time: 2017-09-07 09:31:53
XMind Distribution Pack: cathy_win32
XMind Build ID: R3.7.3.201708180239
Operating System: Windows 10 10.0 (x86)
Platform: win32.win32.x86
Language: en
Country: AU

== Product ==
Product ID: org.xmind.cathy.product
Application ID: org.xmind.cathy.application
Launcher: XMind

Command Line Arguments: -os
 win32
 -ws
 win32
 -arch
 x86
 -showsplash
 -launcher
 C:\Program Files (x86)\XMind\XMind.exe
 -name
 XMind
 --launcher.library
 C:\Program Files (x86)\XMind\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_1.1.400.v20160518-1444\eclipse_1617.dll
 -startup
 C:\Program Files (x86)\XMind\\plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
 --launcher.overrideVmargs
 -configuration
 @user.home/Application Data/XMind/configuration-cathy_win32-R3.7.3.201708180239
 -data
 @user.home/Application Data/XMind/workspace-cathy
 -eclipse.keyring
 @user.home/Application Data/XMind/secure_storage
 D:\src\miner-explorer\docs\AEL2.xmind
 -vm
 C:\Program Files (x86)\XMind\jre\bin\client\jvm.dll
 
VM Arguments: -Dfile.encoding=UTF-8
 -Xms128m
 -Xmx1024m
 -XX:MaxPermSize=256m
 -Djava.class.path=C:\Program Files (x86)\XMind\\plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
 

== Java Properties ==
Java Version: 1.8.0_92
Java Vendor: Oracle Corporation
Java Runtime: Java(TM) SE Runtime Environment
    Version: 1.8.0_92-b14
Java VM: Java HotSpot(TM) Client VM
    Version: 25.92-b14
    Vendor: Oracle Corporation
    Info: mixed mode

**Comment by maciejmatuszak** [comment]
Been poking around the code and as I can see the SVG's are used for relationship arrows.  Sure enough when I remove arrows all is ok, put just one arrow back and the problem is back.
Accidentally I discovered another bug, when you copy paste the nodes, the relationships are not copied...

**Comment by Shawn1** [comment]
Hello maciejmatuszak,

We had fixed it in our previous release version(XMind 8 Update 5). Please try.
