### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by leader4** [xmindltd/xmind#302]
java.lang.ClassCastException: org.json.JSONObject$Null cannot be cast to java.lang.String
	at org.xmind.ui.internal.zen.ManifestDeserializer.deserialize(ManifestDeserializer.java:39)
	at org.xmind.ui.internal.zen.ZenDeserializer.deserializeManifest(ZenDeserializer.java:194)
	at org.xmind.ui.internal.editor.LocalFileWorkbookRef.doLoadWorkbookFromJson(LocalFileWorkbookRef.java:461)
	at org.xmind.ui.internal.editor.LocalFileWorkbookRef.doLoadWorkbookFromURI(LocalFileWorkbookRef.java:422)
	at org.xmind.ui.internal.editor.AbstractWorkbookRef.doLoadWorkbook(AbstractWorkbookRef.java:279)
	at org.xmind.ui.internal.editor.AbstractWorkbookRef.doOpen(AbstractWorkbookRef.java:259)
	at org.xmind.gef.ui.editor.Editable.open(Editable.java:389)
	at org.xmind.ui.internal.editor.LocalFileWorkbookRef.open(LocalFileWorkbookRef.java:870)
	at org.xmind.ui.internal.editor.MindMapEditor$4.run(MindMapEditor.java:634)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

Severity: error
Plug-in ID: org.xmind.ui.mindmap
Code: 0

== Environment ==
Time: 2017-11-14 17:11:13
XMind Distribution Pack: cathy_macosx
XMind Build ID: R3.7.5.201709290120
Operating System: Mac OS X 10.12.6 (x86_64)
Platform: macosx.cocoa.x86_64
Language: zh
Country: CN

== Product ==
Product ID: org.xmind.cathy.product
Application ID: org.xmind.cathy.application
Launcher: XMind

Command Line Arguments: -os
 macosx
 -ws
 cocoa
 -arch
 x86_64
 -showsplash
 -launcher
 /Applications/XMind.app/Contents/MacOS/XMind
 -name
 XMind
 --launcher.library
 /Applications/XMind.app/Contents/MacOS//../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.400.v20160518-1444/eclipse_1615.so
 -startup
 /Applications/XMind.app/Contents/MacOS//../Eclipse/plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
 --launcher.overrideVmargs
 -configuration
 @user.home/Library/XMind/configuration-cathy_macosx-R3.7.5.201709290120
 -data
 @user.home/Library/XMind/workspace-cathy
 -eclipse.keyring
 @user.home/Library/XMind/secure_storage
 -psn_0_1335622
 -vm
 /Applications/XMind.app/Contents/Eclipse/jre/lib/jli/libjli.dylib
 
VM Arguments: -Dfile.encoding=UTF-8
 -XstartOnFirstThread
 -Djava.class.path=/Applications/XMind.app/Contents/MacOS//../Eclipse/plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
 

== Java Properties ==
Java Version: 1.8.0_92
Java Vendor: Oracle Corporation
Java Runtime: Java(TM) SE Runtime Environment
    Version: 1.8.0_92-b14
Java VM: Java HotSpot(TM) 64-Bit Server VM
    Version: 25.92-b14
    Vendor: Oracle Corporation
    Info: mixed mode

**Comment by leader4** [comment]
1. Some files can not be opened 
2. I can't use 【file】 → 【open】
