### ISSUE TITLE
Can not start (Commons/data/configuration-cathy not found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#78]
```
What steps will reproduce the problem?
1. mkdir /tmp/xmind ; cd /tmp/xmind ; download and unpack
xmind-portable-3.0.3.200904291819.zip
   (BTW: it is bad behavoir not to make "top" directory souch as "xmind"
    or "xmind-3.0.3"
2. cd "XMind for Linux" and run ./xmind - it run OK
3. cd / ; and "/tmp/xmind/XMind for Linux/xmind"  and it fails

What is the expected output?
XMind GUI

What do you see instead?
Errmessage
=======================================================
!SESSION 2009-05-25 09:18:02.914
-----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_0
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86, WS=gtk, NL=cs_CZ
Command-line arguments:  -os linux -ws gtk -arch x86

!ENTRY org.eclipse.osgi 4 0 2009-05-25 09:18:03.366
!MESSAGE Error reading configuration:
/Commons/data/configuration-cathy/org.eclipse.osgi/.manager/.fileTableLock
(No such file or directory)
!STACK 0
java.io.FileNotFoundException:
/Commons/data/configuration-cathy/org.eclipse.osgi/.manager/.fileTableLock
(No such file or directory)
    at java.io.RandomAccessFile.open(Native Method)
    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:233)
    at
org.eclipse.core.runtime.internal.adaptor.Locker_JavaNio.lock(Locker_JavaNio.jav
a:32)
    at
org.eclipse.osgi.storagemanager.StorageManager.lock(StorageManager.java:389)
    at
org.eclipse.osgi.storagemanager.StorageManager.open(StorageManager.java:687)
    at
org.eclipse.osgi.internal.baseadaptor.BaseStorage.initFileManager(BaseStorage.ja
va:208)
    at
org.eclipse.osgi.internal.baseadaptor.BaseStorage.initialize(BaseStorage.java:14
2)
    at
org.eclipse.osgi.baseadaptor.BaseAdaptor.initializeStorage(BaseAdaptor.java:124)
    at
org.eclipse.osgi.framework.internal.core.Framework.initialize(Framework.java:180
)
    at
org.eclipse.osgi.framework.internal.core.Framework.<init>(Framework.java:152)
    at org.eclipse.osgi.framework.internal.core.OSGi.createFramework(OSGi.java:90)
    at org.eclipse.osgi.framework.internal.core.OSGi.<init>(OSGi.java:31)
    at
org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:286)
    at
org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:175)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:549)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:504)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1236)

=======================================================


What version of the product are you using?

xmind-3.0.3.200904291819

On what operating system?

Ubuntu 9.04


Please provide any additional information below.


```

Original issue reported on code.google.com by `kli...@gmail.com` on 25 May 2009 at 7:22

**Comment by frankshaka** [comment]
Closing this issue as it is too old.
